### ISSUE TITLE
Can you show a sample config for docker env variables instead of config.yml?

### ISSUE THREAD

**Issue by ovizii** [mskian/gotify-push#7]
I tried translating your instructions:

```
server:
  cors:
    alloworigins:
        - "chrome-extension://cbegkpikakpajcaoblfkeindhhikpfmd"
    allowmethods:
        - "GET"
        - "POST"
    allowheaders:
        - "Authorization"
        - "content-type"
  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
      - "cbegkpikakpajcaoblfkeindhhikpfmd"

```

like this:

```
    environment:
      - GOTIFY_SERVER_CORS_ALLOWORIGINS="- \"chrome-extension://cbegkpikakpajcaoblfkeindhhikpfmd\""
      - GOTIFY_SERVER_CORS_ALLOWMETHODS="- \"GET\"\n- \"POST\""
      - GOTIFY_SERVER_CORS_ALLOWHEADERS="- \"Authorization\"\n- \"content-type\""
      - GOTIFY_SERVER_STREAM_ALLOWEDORIGINS="cbegkpikakpajcaoblfkeindhhikpfmd"

```

but now gotify stops with an error when starting:

```
docker-compose  logs -f
Attaching to gotify
gotify    | Starting Gotify version 2.0.23@2021-06-19-10:08:25
gotify    | panic: yaml: unmarshal errors:
gotify    |   line 1: cannot unmarshal !!str `cbegkpi...` into []string
gotify    |
gotify    | goroutine 1 [running]:
gotify    | github.com/gotify/server/v2/config.Get(0xc0000a2150)
gotify    |     /proj/config/config.go:68 +0x2d7
gotify    | main.main()
gotify    |     /proj/app.go:34 +0x252
gotify exited with code 2

```

any help please?

**Comment by ovizii** [comment]
Ok, I think I got it working with this:

```
    environment:
      GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \"chrome-extension://cbegkpikakpajcaoblfkeindhhikpfmd\""
      GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
      GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\""
      GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \"cbegkpikakpajcaoblfkeindhhikpfmd\""

```
